### ISSUE TITLE
Loading from Sqlite

### ISSUE THREAD

**Issue by samsoft00** [TechFreak/WizardPager#8]
@TechFreak i've been working on this library for the past view days to create a student form. is there anyway i can load data from sqlite into the wizard and what the student select in the first page will determine what student see in the next page for MultipleFixedChoicePage and SingleFixedChoicePage??

**Comment by TechFreak** [comment]
Hi samsoft00, I recommend you load up your data from Sqlite before you create your wizard model.

After that just fill the SingleFixedChoicePage or MultipleFixedChoicePage as you want. e.g.:
