### ISSUE TITLE
How to use ImagePage?

### ISSUE THREAD

**Issue by Wirwing** [TechFreak/WizardPager#9]
I am trying to add image page to wizard. Pick chooser/capture works, but I don't know how to handle activity's result or set page value.

Thanks in advance!

**Comment by TechFreak** [comment]
Hi,

If you want to set the page's value you need to supply a valid URI. If you need more info on URIs, checkout the content on content providers on android docs (http://developer.android.com/guide/topics/providers/content-providers.html)
